/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ebayproject;

import java.util.HashMap;
import java.util.List;
import javax.swing.JCheckBox;

/**
 *
 * @author nbevacqu
 */
public class HomeSelection extends javax.swing.JPanel {

    /**
     * Creates new form HomeSelection
     */
    public HomeSelection(HashMap<String, String> hm, List<JCheckBox> checkboxes, 
            Runnable checkboxSelectedRunnable, HashMap<JCheckBox, HomeSelection> mapCheckboxToSearchPattern) {
        initComponents();
        checkboxes.add(jCheckBox1);
        this.checkboxSelectedRunnable = checkboxSelectedRunnable;
        data = hm;
        if(data.containsKey("name")) {
            jCheckBox1.setText(data.get("name"));
        } else {
            jCheckBox1.setText("name of search pattern here");
            data.put("name", "name of search pattern here");
        }
        mapCheckboxToSearchPattern.put(jCheckBox1, this);
        System.out.println("HomeSelection constructor");
    }
    
    public HashMap<String, String> getData() {
        return data;
    }
    
    public void updateLabels() {
        this.jCheckBox1.setText(data.get("name"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();

        jCheckBox1.setText("Search Pattern Name Here");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jCheckBox1)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        javax.swing.SwingUtilities.invokeLater(checkboxSelectedRunnable);
        //checkboxSelectedRunnable.run();
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private HashMap<String, String> data;
    private Runnable checkboxSelectedRunnable;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    // End of variables declaration//GEN-END:variables
}
